apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-prov-release-cache
  namespace: storage-system
spec:
  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      remediateLastFailure: true
  interval: 1h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-repo
        namespace: storage-system
  targetNamespace: storage-system
  values:
    replicaCount: 2
    strategyType: Recreate
    nfs:
      server: "10.10.2.1"
      path: /srv/cache/docker-cache
      mountOptions:
      volumeName: nfs-cache-provisionner
      # Reclaim policy for the main nfs volume
      reclaimPolicy: Retain
    # For creating the StorageClass automatically:
    storageClass:
      create: true
      name: nfs-cache
      provisionerName: k8s-sigs.io/cache-nfs-subdir-external-provisioner
      allowVolumeExpansion: true
      # Method used to reclaim an obsoleted volume
      reclaimPolicy: Delete
      # When set to false your PVs will not be archived by the provisioner upon deletion of the PVC.
      archiveOnDelete: true
      # Specifies a template for creating a directory path via PVC metadata's such as labels, annotations, name or namespace.
      # Ignored if value not set.
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
      # Set access mode - ReadWriteOnce, ReadOnlyMany or ReadWriteMany
      accessModes: ReadWriteOnce
      # Set volume bindinng mode - Immediate or WaitForFirstConsumer
      volumeBindingMode: Immediate
