apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-repo
  namespace: cert-manager
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: 'v1.12.1'
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
  targetNamespace: cert-manager
  values:
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: 8.8.8.8:53,1.1.1.1:53