apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-ovh-repo
  namespace: cert-manager
spec:
  interval: 24h
  url: https://aureq.github.io/cert-manager-webhook-ovh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-ovh-release
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      version: '0.5.0'
      sourceRef:
        kind: HelmRepository
        name: cert-manager-ovh-repo
  targetNamespace: cert-manager
  values:
    groupName: droso-ovh
    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager-cert-manager-release
