apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deemix-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-docker
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deemix
  labels:
    app: deemix
spec:
  selector:
    matchLabels:
      app: deemix
  template:
    metadata:
      labels:
        app: deemix
        np-ingress-controller-web: allow
        np-internet: allow
    spec:
      containers:
        - name: deemix
          image: registry.gitlab.com/bockiii/deemix-docker
          ports:
            - name: web
              containerPort: 6595
          volumeMounts:
            - mountPath: /downloads
              name: nas-media-data
              subPath: Downloads/Music
              readOnly: false
            - mountPath: /config
              name: deemix-config
              readOnly: false
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: DEEMIX_SINGLE_USER
              value: "true"
      volumes:
        - name: deemix-config
          persistentVolumeClaim:
            claimName: deemix-config
        - name: nas-media-data
          persistentVolumeClaim:
            claimName: nas-media-data-media
---
apiVersion: v1
kind: Service
metadata:
  name: deemix
spec:
  ports:
    - protocol: TCP
      name: web
      port: 6595
  selector:
    app: deemix
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: deemix
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`deemix.REDACTED`)
      kind: Rule
      middlewares:
        - name: forwardauth-authelia
          namespace: auth
      services:
        - name: deemix
          port: 6595
  tls:
    secretName: REDACTED-cert
