apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-controller
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-controller
  path: ./k8s/apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: kube-infra-sops-age