apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/cluster/manifests/infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true