apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: testing
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: testing
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        np-ingress-controller-web: allow
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: testing
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`10.10.100.1`) && PathPrefix(`/test`)
      kind: Rule
      services:
        - name: whoami
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: testing
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whoami.REDACTED`)
      kind: Rule
      services:
        - name: whoami
          port: 80
  tls:
    secretName: REDACTED-cert