---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1h
  path: ./k8s/infra/cert-manager/setup
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-cert-manager
  serviceAccountName: kustomize-controller
  interval: 1m
  path: ./k8s/infra/cert-manager/issuers
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: kube-infra-sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-cert-manager-issuers
  serviceAccountName: kustomize-controller
  interval: 1m
  path: ./k8s/infra/cert-manager/certs
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true