apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-flux
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1h
  path: ./k8s/infra/flux
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: kube-infra-sops-age
