apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1h
  path: ./k8s/infra/storage
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
