apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../common
  - .storage
  - deemix
  - qbittorrent
  - navidrome
  - lms
  - photoprism
  - readerstore
  - tachidesk
  - jdownloader
  - zogwine
  - downloader
  - ganymede
namespace: media
