kind: Deployment
apiVersion: apps/v1
metadata:
  name: cyberchef
  labels:
    app: cyberchef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
        np-ingress-controller-web: allow
    spec:
      containers:
        - name: cyberchef
          image: git.REDACTED/droso/cyberchef
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cyberchef
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: cyberchef
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cyberchef
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cyberchef.REDACTED`)
      kind: Rule
      middlewares:
        - name: forwardauth-authelia
          namespace: auth
      services:
        - name: cyberchef
          port: 8080
  tls:
    secretName: REDACTED-cert
