---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      remediateLastFailure: true
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: '23.0.x'
  interval: 1h
  releaseName: traefik
  targetNamespace: kube-system
  values:
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    additionalArguments:
      - "--accesslog=true"
      - "--log.level=DEBUG"
      - "--providers.kubernetescrd.allowCrossNamespace=true"
    #  - "--providers.file.filename=/config/dynamic-conf.yaml"
    log:
      general:
        level: DEBUG
      access:
        enabled: true
    #volumes:
    #  - name: traefik-config
    #    mountPath: /config
    #    type: configMap
    ports:
      web:
        port: 80
        exposedPort: 80
        expose: true
        protocol: TCP
      websecure:
        port: 443
        exposedPort: 443
        expose: true
        protocol: TCP
      https-wan:
        port: 444
        exposedPort: 444
        expose: true
        protocol: TCP
      mqtts:
        port: 8883
        exposedPort: 8883
        expose: true
        protocol: TCP
    ingressRoute:
      dashboard:
        enabled: false
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: lan
