apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      remediateLastFailure: true
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  interval: 1h
  releaseName: metallb
  values:
    prometheus:
      scrapeAnnotations: true
    speaker:
      enabled: true
    #  nodeSelector:
      #frr:
      #  enabled: false
