apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-le-staging
  namespace: cert-manager
spec:
  acme:
    email: contact@REDACTED
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-le-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-le-prod
  namespace: cert-manager
spec:
  acme:
    email: contact@REDACTED
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-le-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
