apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbackup-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: nfs-docker
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: dbackup
  labels:
    app: dbackup
spec:
  schedule: "0 3 1 * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dbackup
            np-postgres: allow
            np-mysql: allow
        spec:
          containers:
            - name: dbackup
              image: ghcr.io/drosocode/dbackup
              volumeMounts:
                - mountPath: /data
                  name: data
                - name: config
                  readOnly: true
                  mountPath: /app
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: dbackup-data
            - name: config
              secret:
                secretName: dbackup-config
          restartPolicy: Never
