apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nas-user
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: nfs-nas-user
  nfs:
    server: "10.10.2.1"
    path: /srv/data/Homes
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-user-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-nas-user
