# allow iot lan access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-local-iot
spec:
  podSelector:
    matchLabels:
      np-local-iot: allow
  policyTypes:
    - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.20.0.0/16
