# allow lan access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-local-lan
spec:
  podSelector:
    matchLabels:
      np-local-lan: allow
  policyTypes:
    - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.1.0/24
