# allow server lan access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-local-server
spec:
  podSelector:
    matchLabels:
      np-local-server: allow
  policyTypes:
    - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.10.0.0/16
