apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-env
data:
  GF_RENDERING_SERVER_URL: http://localhost:8081/render
  GF_RENDERING_CALLBACK_URL: http://localhost:3000/
  GF_EXTERNAL_IMAGE_STORAGE_PROVIDER: local
  GF_SERVER_ROOT_URL: https://graph.REDACTED
  GF_UNIFIED_ALERTING_ENABLED: 'true'
  GF_UNIFIED_ALERTING_SCREENSHOTS_ENABLED: 'true'
  GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: 'true'
  GF_UNIFIED_ALERTING_SCREENSHOTS_UPLOAD_EXTERNAL_IMAGE_STORAGE: 'true'
  GF_AUTH_GENERIC_OAUTH_ENABLED: 'true'
  GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: 'true'
  GF_AUTH_GENERIC_OAUTH_NAME: Authelia
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: 6w2somb5FPuPUTsG5C4JbyXdRFEVKRG1iJ3KO2Xj
  GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email groups
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://auth.REDACTED/api/oidc/authorization
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://auth.REDACTED/api/oidc/token
  GF_AUTH_GENERIC_OAUTH_API_URL: https://auth.REDACTED/api/oidc/userinfo
  GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: preferred_username
  GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: groups
  GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: name
  GF_AUTH_GENERIC_OAUTH_USE_PKCE: "true"
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups[*], 'monitoring-admin') && 'Admin' || contains(groups[*], 'monitoring-admin') && 'Editor' || 'Viewer'
