apiVersion: v1
kind: ConfigMap
metadata:
  name: asterisk-config
data:
  extensions.conf: |-
    [general] 
    static=yes 
    writeprotect=no 
    clearglobalvars=no 
    include=>parkedcalls 

    [globals] 
    CONSOLE=Console/dsp ; Console interface for demo 
    IAXINFO=guest ; IAXtel username/password 
    TRUNK=DAHDI/G2 ; Trunk interface 
    TRUNKMSD=1 ; MSD digits to strip (usually 1 or 0) 
    include=>parkedcalls 

    [incoming] ;Contexte appelé depuis le fichier sip.conf 
    exten => s,1,NoOp(${CALLERID}) 
    exten => s,2,Dial(SIP/1000&SIP/1001&SIP/1002&SIP/1005, 20) ;Action lors d'un appel, dans ce cas appeler les postes: 1000, 1001, 1002 et 1003, 1004 en même temps 

    [outgoing]
    ; appels locaux en 1XXX
    exten => _1XXX,1,Dial(SIP/${EXTEN},20,tT)

    ; minitel 36XX
    ;exten => 3615,1,Softmodem(192.168.1.9, 8289, v(V23)ld(8)s(1))
    exten => 3615,1,Softmodem(10.10.2.1, 23, v(V23)ld(8)s(1))

    ;exten => _1XXX,2,Voicemail(${CALLERID(num)}) 
    ;exten => _1XXX,3,VoiceMail(${EXTEN}@work) 

    ;Numéro de la boite vocale 
    ;exten => 888,1,VoiceMailMain(${CALLERID(num)}@work) 

    ; appels sortants depuis les postes SIP
    exten => _0[1-9]xxxxxxxx, 1, Dial(SIP/SPA3000-PSTN/${EXTEN},tT)

  rtp.conf: |-
    [general]
    ;
    ; RTP start and RTP end configure start and end addresses
    ;
    ; Defaults are rtpstart=5000 and rtpend=31000
    ;
    rtpstart=10000
    rtpend=20000

  sip.conf: |-
    [general] 
    context=incoming	; Default context for incoming calls 
    allowoverlap=no	; Disable overlap dialing support. (Default is yes) 
    udpbindaddr=0.0.0.0	; IP address to bind UDP listen socket to (0.0.0.0 binds to all) 
    tcpenable=no	; Enable server for incoming TCP connections (default is no) 
    tcpbindaddr=0.0.0.0	; IP address for TCP server to bind to (0.0.0.0 binds to all interfaces) 
    srvlookup=no	; Enable DNS SRV lookups on outbound calls 
    language=fr	; Default language setting for all users/peers 
    externip=10.10.100.41	;IP Publique 
    ;localnet=192.168.1.0/255.255.255.0 
    localnet=10.10.0.0/255.255.0.0 
    defaultexpirey=1800 
    dtmfmode=auto 
    qualify=yes 
    bindport=5060 
    bindaddr=0.0.0.0
    canreinvite=no 
    registertimeout=30 
    registerattempts=0 
    allowguest=yes 
    nat=no 
    allow=all 
    allowexternaldomain = yes 
    videosupport=yes
    accept_outofcall_message=yes 
    outofcall_message_context=message
    auth_message_requests=yes
    #include sip.user.conf

